baseURL = 'https://noiseandpatterns.org/'
languageCode = 'en-us'
title = 'Nose And Patterns'
theme = 'papermod'



[[menu.main]]
identifier = "posts"
name = "Notes"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3
